import os
import uuid
import json
from datetime import datetime
from html import escape

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont


def register_bangla_font():
    font_paths = [
        r"C:\Windows\Fonts\Nirmala.ttf",
        r"C:\Windows\Fonts\NirmalaB.ttf",
        r"C:\Windows\Fonts\kalpurush.ttf"
    ]

    for font_path in font_paths:
        if os.path.exists(font_path):
            pdfmetrics.registerFont(TTFont("BanglaFont", font_path))
            return "BanglaFont"

    return "Helvetica"


def format_data(data):
    if data is None:
        return "Not provided"

    if isinstance(data, (dict, list)):
        return json.dumps(data, indent=2, ensure_ascii=False)

    return str(data)


def add_section(story, styles, title, content):
    story.append(Paragraph(f"<b>{escape(title)}</b>", styles["BanglaHeading"]))
    story.append(Spacer(1, 8))

    formatted_content = format_data(content)
    safe_text = escape(formatted_content).replace("\n", "<br/>")

    story.append(Paragraph(safe_text, styles["BanglaBody"]))
    story.append(Spacer(1, 16))


def create_health_report(report_data: dict):
    output_folder = "generated_reports"
    os.makedirs(output_folder, exist_ok=True)

    file_name = f"health_report_{uuid.uuid4().hex}.pdf"
    file_path = os.path.join(output_folder, file_name)

    font_name = register_bangla_font()

    base_styles = getSampleStyleSheet()

    styles = {
        "Title": ParagraphStyle(
            "CustomTitle",
            parent=base_styles["Title"],
            fontName=font_name,
            fontSize=18,
            leading=24
        ),
        "BanglaHeading": ParagraphStyle(
            "BanglaHeading",
            parent=base_styles["Heading2"],
            fontName=font_name,
            fontSize=13,
            leading=18,
            spaceAfter=6
        ),
        "BanglaBody": ParagraphStyle(
            "BanglaBody",
            parent=base_styles["BodyText"],
            fontName=font_name,
            fontSize=10,
            leading=15
        )
    }

    doc = SimpleDocTemplate(
        file_path,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    story = []

    story.append(Paragraph("AI Healthcare Assistant Report", styles["Title"]))
    story.append(Spacer(1, 20))

    story.append(Paragraph(
        f"Generated on: {datetime.now().strftime('%d %B %Y, %I:%M %p')}",
        styles["BanglaBody"]
    ))
    story.append(Spacer(1, 20))

    add_section(story, styles, "Patient Information", {
        "patient_name": report_data.get("patient_name"),
        "age": report_data.get("age"),
        "gender": report_data.get("gender")
    })

    add_section(story, styles, "Symptoms", report_data.get("symptoms"))

    add_section(story, styles, "AI Triage Result", report_data.get("triage_result"))

    add_section(story, styles, "Vitals Analysis", report_data.get("vitals_result"))

    add_section(story, styles, "Lab Report Analysis", report_data.get("lab_result"))

    add_section(story, styles, "Final Advice", report_data.get("final_advice"))

    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "Safety Note: This report is generated by an AI-assisted demo system. "
        "It is not a final medical diagnosis. Please verify with a doctor or qualified health worker.",
        styles["BanglaBody"]
    ))

    doc.build(story)

    return {
        "file_path": file_path,
        "file_name": file_name
    }